name: Stage the app

on: 
  pull_request:
    types: [labeled]
env:
  DOCKER_IMAGE_NAME: EunhoKang-azure-ttt
  IMAGE_REGISTRY_URL: docker.pkg.github.com
  #################################################
  ### USER PROVIDED VALUES ARE REQUIRED BELOW   ###
  #################################################
  if: contains(github.event.pull_request.labels.*.name, 'peacock')
  #################################################
  ### REPLACE USERNAME WITH GH USERNAME         ###
  AZURE_WEBAPP_NAME: EunhoKang-ttt-app
  #################################################
jobs:
  build:
    runs-on: ubuntu-latest
